name = "remix-cloudflare-stack"
type = "javascript"
workers_dev = true
# account_id = "Or specified with process.env.CF_ACCOUNT_ID"
# zone_id = "Or specified with process.env.CF_ZONE_ID"
# route = "example.com/*"

kv_namespaces = [
  {binding = "USERS", id = "0fa51d314fe643d9a7035436b4ad5b72"},
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "./build/index.js"

[build.upload]
dir = "./dist"
format = "modules"
main = "./worker.mjs"
