name = "remix-cloudflare-stack"
type = "javascript"
usage_model = "unbound"
workers_dev = true
# account_id = "Or specified with process.env.CF_ACCOUNT_ID"
# zone_id = "Or specified with process.env.CF_ZONE_ID"
# route = "example.com/*"

[durable_objects]
bindings = [
  {name = "USER", class_name = "UserDurableObject"},
  {name = "NOTE", class_name = "NoteDurableObject"},
]

[[migrations]]
new_classes = ["NoteDurableObject", "UserDurableObject"]
tag = "v1"

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build"
watch_dir = "./build/index.js"

[build.upload]
dir = "./dist"
format = "modules"
main = "./worker.mjs"
